
interface ProductType {
  id:number,
  img:string,
  trending?:boolean,
  topRated?:boolean,
  bestSeller?: boolean,
  variants?: [{
    key: string,
    value: string[],
  }],
  new?:boolean,
  banner?:boolean,
  banner_img?:string,
  sale_of_per?:number,
  related_images?:string[],
  thumb_img?:string,
  big_img?:string,
  parentCategory:string,
  category:string,
  brand:string,
  title:string,
  price:number,
  old_price?:number,
  rating:number,
  quantity:number,
  orderQuantity?:number,
  sm_desc:string,
  sizes?:string[],
  colors:string[],
  weight?:number,
  dimension?:string,
  reviews?: {
    clientEmail: string,
    reviewComment: string,
    replyEmail: string,
    replyComment: string,
    score: number,
    showReply: boolean,
  }[],
  productDescription?:string,
}

export default ProductType;